//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedMasterFinalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSession
    {
        public int ClassSessionId { get; set; }
        public string GroupId { get; set; }
        public string Day { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
